### ISSUE TITLE
奇形怪状的bug

### ISSUE THREAD

**Issue by unclay** [unclay/blog#4]
## 收集各种奇怪的bug

**Comment by unclay** [comment]
安卓机，使用rem，小圆点不圆

```css
.circle {
  display: inline-block;
  width: 0.5rem;
  height: 0.5rem;
  border-radius: 100%;
  background: red;
}
```

```html
<div class="circle"></div>
<div class="circle"></div>
<div class="circle"></div>
<div class="circle"></div>
```

![qq 20171227181923](https://user-images.githubusercontent.com/10149074/34378760-915da7b2-eb32-11e7-9962-b12fd1f58e30.png)

解决方法：用px，或者用图片（png、svg）

附加circle.svg
```svg
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="200" height="200" version="1.1"
xmlns="http://www.w3.org/2000/svg">
   <circle cx="100" cy="100" r="100" fill="#F76260"/>
</svg>
```
